# Generated by Django 4.2.21 on 2025-06-30 09:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='privacy_settings',
            field=models.JSONField(default=dict, help_text='Privacy settings for analytics and progress sharing'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('completion', 'Course Completion'), ('achievement', 'Achievement Certificate'), ('participation', 'Participation Certificate')], default='completion', max_length=20)),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificate_data', models.JSONField(default=dict, help_text='Certificate template data')),
                ('is_verified', models.BooleanField(default=True)),
                ('verification_code', models.CharField(max_length=50, unique=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='progress.enrollment')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_date'],
            },
        ),
    ]
