# Generated by Django 5.0.14 on 2025-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('paid', 'Paid Enrollment'), ('trial', 'Trial Enrollment'), ('sponsored', 'Sponsored Enrollment')], default='paid', help_text='Type of enrollment (paid, trial, or sponsored)', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='trial_boundaries',
            field=models.JSONField(default=dict, help_text="Trial access boundaries (e.g., {'max_lessons': 2, 'max_modules': 1})"),
        ),
    ]
