# Generated by Django 4.2.21 on 2025-07-11 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_enrollment_privacy_settings_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
    ]
