# Generated by Django 5.0.14 on 2025-07-27 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_delete_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='progress.enrollment'),
        ),
    ]
