# Generated by Django 5.0.14 on 2025-07-31 21:01

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import pyuploadcare.dj.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, choices=[('hnew', 'Home | heading 1'), ('hneww', 'Home | Heading 2'), ('hnewww', 'Home | Heading 3'), ('Programme1', 'Home | Programme1'), ('Programme2', 'Home | Programme2'), ('Programme3', 'Home | Programme3'), ('about_us', 'Home | About Us'), ('mission', 'Home | Our Mission'), ('vision', 'Home | Our Vision'), ('Volunteer', 'Home | Volunteer'), ('footer', 'Home | Footer'), ('aboutUs', 'About Us | About Us'), ('our_Programs', 'Programs | Goddess Care Initiative'), ('reach', 'Programs | Our Reach '), ('team1', 'Our Team | Kelly'), ('team2', 'Our Team | Elsie'), ('team3', 'Our Team | Loise')], max_length=100, unique=True)),
                ('heading', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('slider_image', pyuploadcare.dj.models.ImageField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainProgrames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programe_name', models.CharField(choices=[('Programme1', 'Programe | Programme1'), ('Programme2', 'Programe | Programme2'), ('Programme3', 'Programe | Programme3'), ('Programme4', 'Programe | Programme4')], max_length=100, unique=True)),
                ('programe_description', django_ckeditor_5.fields.CKEditor5Field()),
                ('programe_objective1', django_ckeditor_5.fields.CKEditor5Field()),
                ('programe_objective2', django_ckeditor_5.fields.CKEditor5Field()),
                ('programe_objective3', django_ckeditor_5.fields.CKEditor5Field()),
                ('programe_objective4', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
        migrations.CreateModel(
            name='SecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', django_ckeditor_5.fields.CKEditor5Field()),
                ('title', django_ckeditor_5.fields.CKEditor5Field()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Second Section',
                'verbose_name_plural': 'Second Sections',
            },
        ),
        migrations.CreateModel(
            name='SecondSectionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Second Section Box',
                'verbose_name_plural': 'Second Section Boxes',
            },
        ),
        migrations.CreateModel(
            name='SecondSectionIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(choices=[('icon-vegetable', 'Food Icon'), ('icon-water-1', 'Water Icon'), ('icon-stethoscope', 'Medical Icon')], max_length=50)),
                ('text', django_ckeditor_5.fields.CKEditor5Field()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Second Section Icon',
                'verbose_name_plural': 'Second Section Icons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class', max_length=50)),
                ('color', models.CharField(default='#ff5d15', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_role', models.CharField(choices=[('system_admin', 'System Administrator'), ('course_instructor', 'Course Instructor'), ('teaching_assistant', 'Teaching Assistant'), ('content_creator', 'Content Creator'), ('grader', 'Grader')], default='course_instructor', help_text='Primary instructor role in the system', max_length=30)),
                ('bio', models.TextField(blank=True, help_text='Professional biography and teaching philosophy')),
                ('qualifications', models.TextField(blank=True, help_text='Educational background and certifications')),
                ('years_experience', models.IntegerField(default=0, help_text='Years of teaching/training experience')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('website_url', models.URLField(blank=True, help_text='Personal or professional website')),
                ('office_hours', models.TextField(blank=True, help_text='Available office hours for student consultations')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Instructor verification status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether instructor is currently active')),
                ('can_create_courses', models.BooleanField(default=True, help_text='Permission to create new courses')),
                ('can_manage_assessments', models.BooleanField(default=True, help_text='Permission to create and manage quizzes/assessments')),
                ('can_view_analytics', models.BooleanField(default=True, help_text='Permission to view student analytics and progress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_instructors', to=settings.AUTH_USER_MODEL)),
                ('specializations', models.ManyToManyField(blank=True, help_text='Areas of expertise and specialization', to='users.specialization')),
            ],
            options={
                'verbose_name': 'Instructor Profile',
                'verbose_name_plural': 'Instructor Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('youth_impact_training empowerment', 'youth impact training')], max_length=50)),
                ('program_other', models.CharField(blank=True, help_text="Specify if 'Other' is selected", max_length=200)),
                ('amount_needed', models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('financial_situation', models.CharField(choices=[('unemployed', 'Unemployed'), ('student', 'Student'), ('low_income', 'Low Income'), ('single_parent', 'Single Parent'), ('disabled', 'Person with Disability'), ('refugee', 'Refugee/Asylum Seeker'), ('other', 'Other (Please specify)')], max_length=50)),
                ('financial_situation_other', models.CharField(blank=True, help_text="Specify if 'Other' is selected", max_length=200)),
                ('reason', models.TextField(help_text='Please provide a detailed explanation (minimum 100 characters)', validators=[django.core.validators.MinLengthValidator(100)])),
                ('supporting_document', models.FileField(blank=True, help_text='Optional: Upload supporting documents (PDF, DOC, DOCX, JPG, PNG)', null=True, upload_to='sponsorship_documents/')),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_email', models.EmailField(max_length=254)),
                ('emergency_contact_relationship', models.CharField(help_text='Relationship to you', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for administrators')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Date and time when sponsorship was approved', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin user who approved this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sponsorships', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, help_text='Course for which sponsorship is requested', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_requests', to='courses.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sponsorship_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sponsorship Request',
                'verbose_name_plural': 'Sponsorship Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(default='Edit your Bio!')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending Verification'), ('confirmed', 'Payment Confirmed'), ('expired', 'Payment Expired'), ('partially_paid', 'Partially Paid (Installment)'), ('sponsorship', 'Sponsored Access')], default='unpaid', help_text='Current payment status for YITP courses', max_length=20)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, help_text='Date and time when payment was confirmed', null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('cash', 'Cash Payment'), ('installment', 'Installment Plan'), ('scholarship', 'Scholarship'), ('other', 'Other')], help_text='Method used for payment', max_length=20, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid (in KES)', max_digits=10, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number or transaction ID', max_length=100, null=True)),
                ('payment_notes', models.TextField(blank=True, help_text='Additional notes about payment (admin use)')),
                ('partial_payment_date', models.DateTimeField(blank=True, help_text='Date when partial payment (50%) was made', null=True)),
                ('payment_expiration_date', models.DateTimeField(blank=True, help_text='Date when partial payment access expires (30 days from partial payment)', null=True)),
                ('installment_amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid in first installment (50% of course price)', max_digits=10, null=True)),
                ('total_course_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total course price for installment tracking', max_digits=10, null=True)),
                ('profile_completion_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of profile completion based on filled fields', max_digits=5)),
                ('email_verified', models.BooleanField(default=False, help_text="Whether the user's email has been verified via OTP")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_points', models.IntegerField(default=0, help_text='Total points earned by the user')),
                ('current_streak', models.IntegerField(default=0, help_text='Current consecutive days of learning activity')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest consecutive days of learning activity achieved')),
                ('last_activity_date', models.DateField(blank=True, help_text='Date of last learning activity for streak calculation', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sponsorship_request', models.ForeignKey(blank=True, help_text="Linked sponsorship request if payment status is 'sponsorship'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_profile', to='users.sponsorshiprequest')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role', models.CharField(choices=[('primary_instructor', 'Primary Instructor'), ('co_instructor', 'Co-Instructor'), ('teaching_assistant', 'Teaching Assistant'), ('grader', 'Grader'), ('guest_lecturer', 'Guest Lecturer')], default='teaching_assistant', max_length=30)),
                ('can_edit_content', models.BooleanField(default=True)),
                ('can_manage_enrollments', models.BooleanField(default=True)),
                ('can_grade_assessments', models.BooleanField(default=True)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_communicate_students', models.BooleanField(default=True)),
                ('can_publish_course', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Assignment notes or special instructions')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Instructor Assignment',
                'verbose_name_plural': 'Course Instructor Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('course', 'instructor')},
            },
        ),
    ]
