# Generated by Django 4.2.21 on 2025-06-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_phone_number_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AlterField(
            model_name='sponsorshiprequest',
            name='program',
            field=models.CharField(choices=[('youth_impact_training empowerment', 'youth impact training')], max_length=50),
        ),
    ]
