# Generated by Django 5.0.14 on 2025-08-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_magiclinktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last verification reminder email sent', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminder_emails_stopped',
            field=models.BooleanField(default=False, help_text='Whether reminder emails have been stopped (max reached or user verified)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_reminder_count',
            field=models.IntegerField(default=0, help_text='Number of verification reminder emails sent'),
        ),
    ]
