# Generated by Django 5.0.14 on 2025-08-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_reminder_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text="User's city or region", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, help_text="User's country (detected from phone number or IP)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address used during registration for geolocation', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_source',
            field=models.CharField(choices=[('phone', 'Phone Number'), ('ip', 'IP Address'), ('manual', 'User Provided'), ('unknown', 'Unknown')], default='unknown', help_text='Source of location information', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone_name',
            field=models.CharField(blank=True, help_text="User's timezone (e.g., Africa/Nairobi, America/New_York)", max_length=50, null=True),
        ),
    ]
