# Generated by Django 4.2.21 on 2025-06-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid (in KES)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when payment was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash Payment'), ('installment', 'Installment Plan'), ('scholarship', 'Scholarship'), ('other', 'Other')], help_text='Method used for payment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Additional notes about payment (admin use)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment reference number or transaction ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending Verification'), ('confirmed', 'Payment Confirmed'), ('expired', 'Payment Expired')], default='unpaid', help_text='Current payment status for YITP courses', max_length=20),
        ),
    ]
