# Generated by Django 5.0.14 on 2025-09-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_audio_url_lesson_document_url_and_more'),
        ('users', '0004_add_geographic_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trial_conversion_prompted_at',
            field=models.DateTimeField(blank=True, help_text='Date when user was first prompted to upgrade from trial', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_course',
            field=models.ForeignKey(blank=True, help_text='Course for which trial access was granted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_users', to='courses.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_lessons_accessed',
            field=models.JSONField(default=list, help_text='List of lesson IDs accessed during trial'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_quizzes_taken',
            field=models.JSONField(default=list, help_text='List of quiz IDs taken during trial'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when trial was started', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_status',
            field=models.CharField(choices=[('none', 'No Trial'), ('active', 'Active Trial'), ('expired', 'Trial Expired'), ('converted', 'Converted to Paid')], default='none', help_text='Current trial status for the user', max_length=20),
        ),
    ]
