# Generated by Django 4.2.21 on 2025-07-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's email has been verified via OTP"),
        ),
    ]
