# Generated by Django 5.0.14 on 2026-01-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_make_datetime_fields_timezone_aware'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='heard_about',
            field=models.CharField(choices=[('google', 'Google Search'), ('chatgpt', 'ChatGPT'), ('youtube', 'YouTube'), ('twitter', 'Twitter / X'), ('facebook', 'Facebook'), ('livegreat', 'LiveGreat Foundation'), ('referral', 'Friend / Referral'), ('other', 'Other')], default='other', help_text='How the user heard about YITP', max_length=50),
        ),
    ]
