# Generated by Django 5.0.14 on 2026-01-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_referral_code',
            field=models.CharField(blank=True, help_text='User-specific referral code for sharing registration links', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
