# Generated by Django 5.0.14 on 2025-09-11 10:23

from django.db import migrations, models


def update_quiz_max_attempts(apps, schema_editor):
    """
    Update existing quizzes that have max_attempts=1 (old default) to max_attempts=15 (new default).
    Preserve any custom values that instructors may have set.
    """
    Quiz = apps.get_model('assessments', 'Quiz')

    # Update only quizzes with the old default value of 1
    updated_count = Quiz.objects.filter(max_attempts=1).update(max_attempts=15)

    if updated_count > 0:
        print(f"Updated {updated_count} quiz(es) from 1 to 15 maximum attempts")
    else:
        print("No quizzes needed updating (none had max_attempts=1)")


def reverse_quiz_max_attempts(apps, schema_editor):
    """
    Reverse migration: Update quizzes back to max_attempts=1 if they have max_attempts=15
    """
    Quiz = apps.get_model('assessments', 'Quiz')

    # Only reverse quizzes that have exactly 15 attempts (likely our updated ones)
    reversed_count = Quiz.objects.filter(max_attempts=15).update(max_attempts=1)

    if reversed_count > 0:
        print(f"Reversed {reversed_count} quiz(es) from 15 to 1 maximum attempts")


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        # First update the field default
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(default=15, help_text='Maximum number of attempts allowed (0 for unlimited)'),
        ),
        # Then update existing data
        migrations.RunPython(
            update_quiz_max_attempts,
            reverse_quiz_max_attempts,
        ),
    ]
