# Generated by Django 4.2.21 on 2025-06-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name': 'Posts', 'verbose_name_plural': 'Posts'},
        ),
    ]
