# Generated by Django 4.2.21 on 2025-07-11 18:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rich text content with formatting, images, and interactive elements'),
        ),
    ]
