# Generated by Django 5.1.3 on 2024-12-01 00:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        # This is a fake migration to match production state
        # The actual changes were already applied in production
    ]
