# Generated by Django 5.0.14 on 2025-08-21 22:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_create_intro_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text course description with formatting and media', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_objectives',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='What students will learn - use rich text formatting', verbose_name='Learning Objectives'),
        ),
    ]
