# Generated by Django 5.0.14 on 2025-08-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_url',
            field=models.URLField(blank=True, help_text='URL for audio content'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='document_url',
            field=models.URLField(blank=True, help_text='Uploadcare URL for PDF documents'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text Content'), ('video', 'Video'), ('document', 'Document (PDF)'), ('audio', 'Audio'), ('presentation', 'Presentation'), ('exercise', 'Interactive Exercise'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], max_length=20),
        ),
    ]
